### ISSUE TITLE
Process Not Found Amazon & Simplewall

### ISSUE THREAD

**Issue by podaen** [kyaulabs/win11tweak#21]
Hi,

I followed the md and had two failed installation. The other 30 installations all went well.

- ERROR: The process "Amazon Games UI.exe" not found
- ERROR: The process "simplewall" not found

MSI tomahawk DDR5 Z790
Intel 13600K
OS build 22621

**Comment by kyau** [comment]
If you look in the powershell script that installs all the applications with `chocolatey` you will notice there is a toggle added to the function. This is used as some applications stay open after installation which would halt the progress of the script. This is the message that shows up when it fails to close the application process because it was already closed by the `chocolatey` installation script. This is not so much a failure as just a reporting echo that I choose not to silence like everything else.

**Comment by podaen** [comment]
yeah, but I didn't see them. Can it be that the are not visual? The only msgboxes or windows I had was on installing voicemeeter, fonts and msEdgeRedirect.

**Comment by kyau** [comment]
Sorry I should have elaborated, in the past these applications have intermittently left themselves open after installation. While currently as you are getting an error stating the contrary (they are not staying open after installation, hence the error).

That said any application that does this previously I am worried might again so I never removed the flag being toggled on to attempt to kill the running executable after installation. You can basically think of the error as "process was not running so there was nothing to kill".

**Comment by podaen** [comment]
I understand. Thanks!
