### ISSUE TITLE
It is possible to post to the Winget?

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [kyaulabs/win11tweak#3]
I think it's a good idea. 
Useful tool.
(Microsoft probably won't think so）

**Comment by kyau** [comment]
I am currently in the process of refactoring the repository with proper testing and Git flow as well as adding some major new features, odds are I will try to wrap all of this up before attempting a submission.

That said, I will look into this a bit further. As you say, I think it remains unclear as to whether or not it would get approved since Microsoft is the one that runs the `winget` repositories but we will not know unless we try.

Leaving some links here for myself as reference and for future research into the matter.

https://docs.microsoft.com/en-us/windows/package-manager/package/
https://docs.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example
https://docs.microsoft.com/en-us/windows/package-manager/package/repository
